# Generated by Django 3.1.1 on 2020-10-09 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managebook', '0002_auto_20200926_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(db_index=True, related_name='book', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
    ]
